---
services:
    homepage:
        container_name: glance
        image: glanceapp/glance
        env_file:
          - .env
        volumes:
            - ./config:/app/config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        dns:
          - 10.10.10.10
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.docker.network=proxy"
          - "traefik.http.routers.glanc.entrypoints=https"
          - "traefik.http.routers.glanc.rule=Host(`dash.local.puvvadi.net`)"
          - "traefik.http.routers.glanc.middlewares=default-headers@file, https-redirectscheme@file"
          - "traefik.http.routers.glanc.tls=true"
          - "traefik.http.routers.glanc.service=glanc"
          - "traefik.http.services.glanc.loadbalancer.server.scheme=http"
          - "traefik.http.services.glanc.loadbalancer.server.port=8080"
        networks:
          - proxy
networks:
  proxy:
    external: true
